name: transfer the repo

on:
  push:
    branches:
      - main
  pull_request:
    

jobs:
  scriptworkflow:
    runs-on: self-hosted

    steps:
      - name: Archive the repo
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == "true"
        env:
         CURRENT_PR_REPO: ${{github.repository}}
         PR_NUMBER: ${{github.event.number}}
         shell: bash
        run: |
         sudo apt install -y jq
          echo "jq --version"
          chmod +x ./Archiverepo.sh 
          ./Archiverepo.sh ${{ env.GA_SECRET }} ${{env.CURRENT_PR_REPO}} ${{env.PULL_REQUEST}}
