name: Install Nginx

on:
  push:
    branches:
      - main

jobs:
  install-nginx:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
